// src/scripts/Layout.vue
<template>
  <div class="layout">
    <Navbar />
    <main class="page">
      <router-view />
    </main>
    <Footer />
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import Navbar from 'scripts/components/Navbar.vue';
import Footer from 'scripts/components/Footer.vue';

export default Vue.extend({
  components: {
    Navbar,
    Footer,
  },
});
</script>

// src/scripts/pages/Layout.tsx
import * as React from 'react';
import { Outlet } from 'react-router-dom';
import Header from 'scripts/components/Header';
import Footer from 'scripts/components/Footer';

export default function Layout(): JSX.Element {
  return (
    <div>
      <Header />
      <Outlet />
      <Footer />
    </div>
  );
}

Layout.displayName = 'Layout';
